Vagrant.configure(2) do |config|
  config.vm.box = "leopard/rwtrusty64"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "config/", "/vagrant/config"
  config.vm.synced_folder "www/", "/vagrant/www",  owner: "root", group: "root"

  config.vm.provision "shell", path: "provision.sh"

  # override for leopard/rwtrusty64 default port forwardings
  config.vm.network "forwarded_port", guest: 3000, host: 3100, disabled: true
  config.vm.network "forwarded_port", guest: 1080, host: 1180, disabled: true

  # actual used port forwardings
  config.vm.network "forwarded_port", guest: 80, host: 8080
end
